sudo: false
branches:
  except:
      - servo

language: rust
rust: nightly
script: scripts/travis-build.sh
after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh

notifications:
  webhooks: http://build.servo.org:54856/travis
